server:
  port: 8090

spring:
  # Bean 오버라이드 허용 (MyBatis + JPA 혼용)
  main:
    allow-bean-definition-overriding: true
  # 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_PETMATE?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  # JPA 설정 (메인)
  jpa:
    hibernate:
      ddl-auto: update  # 개발용 (운영에서는 validate 사용)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false # OSIV 비활성화 (성능 최적화)

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [profile, email]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [account_email, profile_nickname, profile_image]
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: NAVER
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [name, email, nickname]
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# MyBatis 설정 (복잡한 쿼리용 보조)
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.petmate.dto
# JWT 설정
jwt:
  secret: djdjdjeueueushshshznmqasdklheqweqwasdasxzc
  issuer: ${JWT_ISSUER}
  expiration: 60000
  refresh-expiration: 604800000
# 로깅 설정
logging:
  level:
    com.petmate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
