-- DB_JWT
CREATE DATABASE DB_PETMATE;
USE DB_PETMATE;

CREATE TABLE MEMBER(
	NO				INT AUTO_INCREMENT,
    ID				VARCHAR(20) UNIQUE,
    PW				VARCHAR(100) NOT NULL,
    MAIL			VARCHAR(50) NOT NULL,
    REG_DATE		DATETIME DEFAULT NOW(),
    MOD_DATE		DATETIME DEFAULT NOW(),
    PRIMARY KEY(NO)
);
SELECT * FROM MEMBER;
DELETE FROM MEMBER;

CREATE TABLE REFRESH_TOKEN(
	NO					INT AUTO_INCREMENT,
    OWNER_NO			INT NOT NULL,
    REFRESH_TOKEN		TEXT NOT NULL,
    REG_DATE			DATETIME DEFAULT NOW(),
    MOD_DATE			DATETIME DEFAULT NOW(),
    PRIMARY KEY(NO)
);

SELECT * FROM REFRESH_TOKEN;
DELETE FROM REFRESH_TOKEN;
